# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/vsmart/msm8953-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter casuarina pine,$(TARGET_DEVICE)),)

endif
